# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b67fd3ffdc3fb5c15febb454d00f5ea1e1aeabcd5879b4cff6131ec8e657800e4e8cddc665e65845e717963b6daff36d48c9dd325799d563815eb4c1f425174

test:
  secret_key_base: 3b301d833a19735193eded2dd25ef519e38b26d1d47f42715b2748e97d8900a24b783db9bbd882518b3895eb8f470b6f58fd6f5d3d5956590712fd084ff716e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
